// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `SocialNetworkConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `data source=localhost\SQLExpress;initial catalog=SocialNetwork;user id=leo;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SocialNetwork.Sample
{
    /// <summary>
    /// A class which represents the FriendList table.
    /// </summary>
	[Table("FriendList")]
	public partial class FriendList
	{
		[Key]
		public virtual int MemberID { get; set; }
		public virtual int FriendID { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime UpdatedAt { get; set; }
		public virtual int UpdatedBy { get; set; }
	}

    /// <summary>
    /// A class which represents the Post table.
    /// </summary>
	[Table("Post")]
	public partial class Post
	{
		[Key]
		public virtual int PostNumber { get; set; }
		public virtual int MeberID { get; set; }
		public virtual string PostContent { get; set; }
		public virtual string PostImage { get; set; }
		public virtual int GoodQuantity { get; set; }
		public virtual int Status { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime UpdatedAt { get; set; }
		public virtual int UpdatedBy { get; set; }
	}

    /// <summary>
    /// A class which represents the PostMsg table.
    /// </summary>
	[Table("PostMsg")]
	public partial class PostMsg
	{
		[Key]
		public virtual int MsgNumber { get; set; }
		public virtual int PostNumber { get; set; }
		public virtual int MemberID { get; set; }
		public virtual string MsgContent { get; set; }
		public virtual string MsgImage { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime UpdatedAt { get; set; }
		public virtual int UpdatedBy { get; set; }
	}

    /// <summary>
    /// A class which represents the VerificationCode table.
    /// </summary>
	[Table("VerificationCode")]
	public partial class VerificationCode
	{
		[Key]
		public virtual int Key { get; set; }
		public virtual string Mail { get; set; }
		public virtual string VCode { get; set; }
		public virtual int Status { get; set; }
		public virtual DateTime? VerificationDate { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime UpdatedAt { get; set; }
		public virtual int UpdatedBy { get; set; }
	}

    /// <summary>
    /// A class which represents the ForgotPassword table.
    /// </summary>
	[Table("ForgotPassword")]
	public partial class ForgotPassword
	{
		[Key]
		public virtual int Key { get; set; }
		public virtual string Guid { get; set; }
		public virtual int MemberID { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime UpdatedAt { get; set; }
		public virtual int UpdatedBy { get; set; }
	}

    /// <summary>
    /// A class which represents the __RefactorLog table.
    /// </summary>
	[Table("__RefactorLog")]
	public partial class RefactorLog
	{
		[Key]
		public virtual Guid OperationKey { get; set; }
	}

    /// <summary>
    /// A class which represents the Member table.
    /// </summary>
	[Table("Member")]
	public partial class Member
	{
		[Key]
		public virtual int MemberID { get; set; }
		public virtual string Account { get; set; }
		public virtual string NickName { get; set; }
		public virtual string Password { get; set; }
		public virtual string Mail { get; set; }
		public virtual string ProfilePhotoURL { get; set; }
		public virtual string BackgoundPhotoURL { get; set; }
		public virtual DateTime? Birthday { get; set; }
		public virtual string Interest { get; set; }
		public virtual string Job { get; set; }
		public virtual string Education { get; set; }
		public virtual int InfoStatus { get; set; }
		public virtual int Status { get; set; }
		public virtual DateTime CreatedAt { get; set; }
		public virtual int CreatedBy { get; set; }
		public virtual DateTime UpdatedAt { get; set; }
		public virtual int UpdatedBy { get; set; }
	}

}
